// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwtqfscyjpgbjorvjgxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3dHFmc2N5anBnYmpvcnZqZ3hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMTE0OTgsImV4cCI6MjA2Nzg4NzQ5OH0.Bw7klY5d6LoxOTs-2letkRS5OH0ut5WJhnSc0NMuXhY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});